version: '3.8'

services:
  n8n:
    build: .
    ports:
      - "5678:5678"
    environment:
      N8N_HOST: ${RAILWAY_STATIC_URL}
      WEBHOOK_URL: ${RAILWAY_STATIC_URL}
      GENERIC_TIMEZONE: America/Sao_Paulo
      N8N_PROTOCOL: https
    restart: unless-stopped